### ISSUE TITLE
Single letter

### ISSUE THREAD

**Issue by joris1995** [vpeschenkov/LetterAvatarKit#14]
First of all: Thanks for the convenient library!

I ran into an issue where my app crashed with a username that consists out of one letter only. Looking into your code, I saw that this is probably due to the fact that the `single` parameter in `LetterAvatarBuilderConfiguration` is always false. I changed it into:

```
open var singleLetter: Bool {
        if let name = username, name.count == 1  {
            return true
        } else {
            return false
        }
    }
```
in my local repo, but I can't push them to your repo to create a pull request. Would you mind giving me permission or changing this yourself?

**Comment by vpeschenkov** [comment]
Hello @joris1995, sorry for the delay. 

Could you give an example of code that raises this crash? Because it seems like this was fixed there #11, and [this test](https://github.com/vpeschenkov/LetterAvatarKit/blob/9eff9ba73241be87ecb5f35d1c0d656667b3bc3c/LetterAvatarKitTests/LetterAvatarBuilderTests.swift#L108) is successful.

Thank you for your help!
