### ISSUE TITLE
Allow for at most 2 letters case?

### ISSUE THREAD

**Issue by danqing** [vpeschenkov/LetterAvatarKit#20]
Is it possible to allow for up to 2 letters? It seems that currently you can only choose between 1 and 3.

**Comment by vpeschenkov** [comment]
Hi @danqing, thank you! If I get you right, I don't see any issue here. 

There is an option to set that an avatar always should have only one letter, otherwise, it builds according to a given name:
- if a given name has 3 name components, there will be 3 letters
- if a given name has 2 name components, there will be 2 letters
- if a given name has 1 name component, there will be 1 letter

The limit is up to 3 letters. If I add a number of letters, I also have to decide which name component to remove.

I think if somebody wants to see 2 letters but has a name with 3 components, it would be better if they decide which part of a name to remove by themselves.
