### ISSUE TITLE
Can I add Transparent Background Color to View 

### ISSUE THREAD

**Issue by NatashaChhibber707** [vpeschenkov/LetterAvatarKit#24]
### Description

Describe your issue here.

### Requirements ( Add Transparent Color to BackgroundColor Array )

* When I set the block Color with alpha (0,0,0,0.12) but it is showing black color instead of     transparent color 

Hexcode -- 1F000000 is Used 

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

LetterAvatarKit version:

iOS version: 13.3.1

**Comment by vpeschenkov** [comment]
Hi @NatashaChhibber707, thank you for your feedback! 

It show black color because of this code:
```
UIGraphicsBeginImageContextWithOptions(
    rect.size,
    false, 
    UIScreen.main.scale
)
```
I think we can add an `opaque` property to [`LetterAvatarBuilderConfiguration`](https://github.com/vpeschenkov/LetterAvatarKit/blob/master/LetterAvatarKit/LetterAvatarBuilderConfiguration.swift) (`false` by default) and re-write that code to be like:
```
UIGraphicsBeginImageContextWithOptions(
    rect.size, 
    configuration.opaque, 
    UIScreen.main.scale
)
```
Also, we have to change a bit the these classes [`LetterAvatarMaker`](https://github.com/vpeschenkov/LetterAvatarKit/blob/master/LetterAvatarKit/LetterAvatarMaker.swift) & [`LetterAvatarMakerExtendable`](https://github.com/vpeschenkov/LetterAvatarKit/blob/master/LetterAvatarKit/LetterAvatarMakerExtendable.swift).

Would you mind taking care of it?
